name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Obter código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar testes
        run: pytest

      - name: Criar artefato
        if: success() && github.ref == 'refs/heads/main'
        run: |
          mkdir artefato
          cp app.py artefato/

      - name: Enviar artefato
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: projeto-aprovado
          path: artefato/
